"""
judge_validator_node.py  (Version 4)
--------------------------------------
Second-pass LLM that validates the primary LLaMA response against:
    1. Retrieved Tavily information (grounding check).
    2. Risk evaluation output (consistency check).
    3. Anti-hallucination policy (no invented diseases, no prescriptions).

V4 changes:
    - Uses regeneration_count for retry routing (max 2 attempts).
    - Sets validated_response on PASS.
    - Sets needs_nutrition_image flag based on risk level.
    - Does NOT regenerate inline — routes back to llm_brain via graph edges.

This node runs AFTER llm_brain_node. Routing handled by graph conditional edges.
"""

from backend.src.tools.groq_llama_tool import call_llama
from backend.src.state.state import TriageState
from backend.src.logging.logger import get_logger, log_event

import asyncio

logger = get_logger("judge_validator")

# Maximum regeneration attempts before force-accepting the response
MAX_REGENERATION_ATTEMPTS = 2


def _sanitize_for_prompt(text: str, max_length: int = 500) -> str:
    """Sanitize text before embedding in LLM prompts to reduce injection risk."""
    # Truncate to prevent excessive prompt length
    sanitized = text[:max_length]
    # Remove common prompt injection patterns
    injection_patterns = [
        "ignore previous", "ignore all", "disregard above",
        "new instructions", "system prompt", "you are now",
    ]
    lower = sanitized.lower()
    for pattern in injection_patterns:
        if pattern in lower:
            sanitized = sanitized.replace(pattern, "[REDACTED]")
            sanitized = sanitized.replace(pattern.upper(), "[REDACTED]")
    return sanitized


async def judge_validator_node(state: TriageState) -> TriageState:
    """
    Validates the current assistant response for hallucination and consistency.

    If validation fails and regeneration_count < MAX_REGENERATION_ATTEMPTS,
    the graph will route back to llm_brain_node for a retry. The routing
    decision is made by the conditional edge function, not this node.

    Args:
        state: Contains messages, retrieved_info, risk_level, risk_score.

    Returns:
        TriageState: Updated with judge_passed, judge_feedback,
                     validated_response, needs_nutrition_image,
                     and regeneration_count.
    """
    messages = state.get("messages", [])
    retrieved_info = state.get("retrieved_info", [])
    risk_level = state.get("risk_level", "")
    risk_score = state.get("risk_score", 0.0)
    regen_count = state.get("regeneration_count", 0)

    # Skip validation for follow-up questions and priority interrupts
    next_action = state.get("next_action", "")
    if next_action in ("ask_followup", "priority_interrupt"):
        state["judge_passed"] = True
        state["judge_feedback"] = ""
        state["validated_response"] = ""
        state["needs_nutrition_image"] = False
        return state

    # Skip validation for X-ray responses — they are generated by the vision model
    # with built-in uncertainty language and disclaimers. Running the judge on them
    # causes false FAIL verdicts ("potential findings" is flagged as an implied diagnosis).
    if state.get("xray_findings"):
        assistant_msgs = [m for m in state.get("messages", []) if m.get("role") == "assistant"]
        state["judge_passed"] = True
        state["judge_feedback"] = ""
        state["validated_response"] = assistant_msgs[-1]["content"] if assistant_msgs else ""
        state["needs_nutrition_image"] = False
        log_event(logger, "judge_xray_passthrough", reason="xray_findings_auto_pass")
        return state

    # Get the V6 structured llm_output to validate
    # In V6, llm_brain writes clinical_summary to llm_output dict
    llm_output = state.get("llm_output", {})
    if not llm_output:
        # Fallback: use last assistant message (xray/vision fast-exit paths)
        assistant_msgs = [m for m in messages if m.get("role") == "assistant"]
        if not assistant_msgs:
            state["judge_passed"] = True
            state["judge_feedback"] = ""
            state["validated_response"] = ""
            state["trigger_nutrition_node"] = False
            return state
        current_response = assistant_msgs[-1]["content"]
    else:
        current_response = llm_output.get("clinical_summary", "")
        if not current_response and messages:
            assistant_msgs = [m for m in messages if m.get("role") == "assistant"]
            current_response = assistant_msgs[-1]["content"] if assistant_msgs else ""

    # Sanitize inputs before embedding in judge prompt (prompt injection mitigation)
    safe_response = _sanitize_for_prompt(current_response, max_length=800)
    safe_context = _sanitize_for_prompt(
        " | ".join(retrieved_info)[:400] if retrieved_info else "None",
        max_length=400
    )

    # ── Validation prompt ──────────────────────────────────────────────────────
    judge_prompt = (
        "You are a STRICT medical triage quality validator.\n\n"
        "Check if the RESPONSE violates ANY of these rules:\n"
        "1. Mentions disease names NOT found in the CONTEXT.\n"
        "2. Prescribes specific medication or dosage.\n"
        "3. Gives a definitive diagnosis (e.g., 'You have X').\n"
        "4. Risk level in response contradicts the ASSESSED RISK.\n"
        "5. Invents symptoms the patient did NOT report.\n\n"
        f"CONTEXT (from medical search): {safe_context}\n"
        f"ASSESSED RISK: {risk_level} ({risk_score}/10)\n"
        f"RESPONSE TO VALIDATE:\n{safe_response}\n\n"
        "If the response is safe and accurate, reply: PASS\n"
        "If it violates any rule, reply: FAIL — [brief reason]\n\n"
        "Verdict:"
    )

    verdict = (await asyncio.to_thread(call_llama, judge_prompt, max_tokens=60)).strip()

    if verdict.upper().startswith("PASS"):
        state["judge_passed"] = True
        state["judge_feedback"] = ""
        state["validated_response"] = current_response

        # Determine if nutrition image is needed (low/moderate risk only)
        state["needs_nutrition_image"] = risk_level.lower() in ("low", "moderate")

        log_event(logger, "judge_validated", result="pass",
                  regeneration_count=regen_count)
        return state

    # ── Validation FAILED ──────────────────────────────────────────────────────
    state["judge_passed"] = False
    state["judge_feedback"] = verdict
    state["regeneration_count"] = regen_count + 1

    log_event(logger, "hallucination_detected",
              feedback=verdict,
              regeneration_count=state["regeneration_count"],
              escalation_flag=True)

    # If we've exhausted regeneration attempts, force-accept with a warning
    if state["regeneration_count"] >= MAX_REGENERATION_ATTEMPTS:
        # Keep judge_passed as False — use force_accepted to signal acceptance
        state["judge_passed"] = False
        state["force_accepted"] = True
        state["validated_response"] = current_response
        state["needs_nutrition_image"] = risk_level.lower() in ("low", "moderate")
        state["judge_feedback"] = f"Force-accepted after {MAX_REGENERATION_ATTEMPTS} attempts. Last issue: {verdict}"
        log_event(logger, "judge_force_accepted",
                  reason="max_regenerations_reached",
                  feedback=verdict[:100])  # Truncate feedback in logs

    return state
